### ISSUE TITLE
All orders page doesn't show all orders

### ISSUE THREAD

**Issue by rjchee** [christodenny/ordr#4]
If there are multiple users, only the last user's items are shown in the All orders page.
![image](https://user-images.githubusercontent.com/9013097/63333814-ea466e00-c2ee-11e9-9176-6fbed986ccba.png)
(the previous user had submitted $64.01 worth of items)

**Comment by christodenny** [comment]
fixed in b75d711fd5bac322ca1fe2c7f837543efd8be5c9
